### ISSUE TITLE
PROGRAMS

### ISSUE THREAD

**Issue by michmue** [michmue/win-backup#92]
## PRIMARY
- [ ] ANKI CONNECT

## TODO: check more apps
- [ ] http://www.lupopensuite.com/bestapps.htm
- [ ] https://portableapps.com/de
- [ ] https://www.chip.de/bildergalerie/Die-50-besten-portablen-Tools-fuer-den-USB-Stick-Galerie_47127780.html

## CLI TOOLS
- [ ] 7zip sdk console
- [ ] maven
- [ ] gradle
- [ ] wolcmd
- [ ] youtube-dl
- [ ] ffmpeg

### TOOLS TO ADD AS DOWNLOAD & SHORTCUT
- [ ] autoruns & autorunsc
- [ ] ShellMenuNew
- [ ] shmnview
- [ ] shexview
- [ ] FileTypesMan
- [ ] iconsext
- [ ] obs-studio

### CREATING SHORTCUT ONLY
- [ ] currently all

## TOOLS
- [ ] wincp
- [ ] treefilesize
- [ ] greenshot?
- [ ] obs-studio
- [ ] sublime text
- [ ] winrar?
- [ ] mp3tag
- [ ] filebot portable
- [ ] deezloader
- [ ] regscanner
- [ ] HWiNFO32 (v4.02)
- [ ] CPU-Z (v1.74)
- [ ] mp3DirectCut
- [ ] Audacity

## USB PROTABLE
- [ ] Firefox Portable
- [ ] GIMP Portable / Paint.Net
- [ ] notepad++
- [ ] 7zip portable
- [ ] h2testw
- [ ] EasyBCD2.4 => bootsec 32bit (HEXEDITOR: PE  = 32bit, PE L = 64bit)

## IMAGE VIEWERS
- [ ] FastStone Image Viewer (v5.5)
- [ ] FastStone MaxView (v2.2)
- [ ] IrfanView (v4.41)
- [ ] XnView (v2.22)
- [ ] Xnview MP
- [ ] NexusImage (v1.1.3)
